# Generated by Django 4.2.9 on 2024-01-28 10:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_map_id_alter_project_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='map',
            name='file',
        ),
        migrations.AddField(
            model_name='map',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
