# Generated by Django 4.2.9 on 2024-02-02 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_project_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='ne_lat',
            field=models.DecimalField(decimal_places=6, default=53.30299905154381, max_digits=9, verbose_name='Northeast Latitude'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='map',
            name='ne_lng',
            field=models.DecimalField(decimal_places=6, default=-6.227385321384242, max_digits=9, verbose_name='Northeast Longitude'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='map',
            name='sw_lat',
            field=models.DecimalField(decimal_places=6, default=53.306172666325566, max_digits=9, verbose_name='Southwest Latitude'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='map',
            name='sw_lng',
            field=models.DecimalField(decimal_places=6, default=-6.220215029692175, max_digits=9, verbose_name='Southwest Longitude'),
            preserve_default=False,
        ),
    ]
