# Generated by Django 4.2.9 on 2024-02-03 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_map_ne_lat_map_ne_lng_map_sw_lat_map_sw_lng'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='map',
            name='ne_lat',
        ),
        migrations.RemoveField(
            model_name='map',
            name='ne_lng',
        ),
        migrations.RemoveField(
            model_name='map',
            name='sw_lat',
        ),
        migrations.RemoveField(
            model_name='map',
            name='sw_lng',
        ),
    ]
